name: Rebase PHP8 branch

on:
  push:
    branches: master

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: php8
          fetch-depth: 0
      - name: Rebase PHP8 branch
        run: |
          git config user.email "${{ github.event.pusher.email }}"
          git config user.name "${{ github.event.pusher.name }}"
          git pull
          git rebase origin/master php8
          git status
          git diff origin/php8
          git push --force-with-lease
